//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCI
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResortResponse", Namespace="http://accessrsi.com/")]
    public partial class ResortResponse : object
    {
        
        private string SessionIDField;
        
        private string RegionCodeField;
        
        private string ResortIDField;
        
        private string ResortNameField;
        
        private double NumberOfBedroomsField;
        
        private string RoomTypeField;
        
        private double NumberOfBathroomsField;
        
        private string KitchenTypeField;
        
        private int MaxOccupancyField;
        
        private int LengthOfStayField;
        
        private int PrivacyOccupancyField;
        
        private string InventoryTypeField;
        
        private string InventoryIDField;
        
        private string CheckInDateField;
        
        private string CheckOutDateField;
        
        private double UnitCostField;
        
        private string CurrencyField;
        
        private bool ErrorField;
        
        private string ErrorMessageField;
        
        private string XMLSendField;
        
        private string XMLReceiveField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResortID
        {
            get
            {
                return this.ResortIDField;
            }
            set
            {
                this.ResortIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ResortName
        {
            get
            {
                return this.ResortNameField;
            }
            set
            {
                this.ResortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double NumberOfBedrooms
        {
            get
            {
                return this.NumberOfBedroomsField;
            }
            set
            {
                this.NumberOfBedroomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RoomType
        {
            get
            {
                return this.RoomTypeField;
            }
            set
            {
                this.RoomTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double NumberOfBathrooms
        {
            get
            {
                return this.NumberOfBathroomsField;
            }
            set
            {
                this.NumberOfBathroomsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string KitchenType
        {
            get
            {
                return this.KitchenTypeField;
            }
            set
            {
                this.KitchenTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int MaxOccupancy
        {
            get
            {
                return this.MaxOccupancyField;
            }
            set
            {
                this.MaxOccupancyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int LengthOfStay
        {
            get
            {
                return this.LengthOfStayField;
            }
            set
            {
                this.LengthOfStayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int PrivacyOccupancy
        {
            get
            {
                return this.PrivacyOccupancyField;
            }
            set
            {
                this.PrivacyOccupancyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string InventoryType
        {
            get
            {
                return this.InventoryTypeField;
            }
            set
            {
                this.InventoryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string InventoryID
        {
            get
            {
                return this.InventoryIDField;
            }
            set
            {
                this.InventoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CheckInDate
        {
            get
            {
                return this.CheckInDateField;
            }
            set
            {
                this.CheckInDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CheckOutDate
        {
            get
            {
                return this.CheckOutDateField;
            }
            set
            {
                this.CheckOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double UnitCost
        {
            get
            {
                return this.UnitCostField;
            }
            set
            {
                this.UnitCostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string XMLSend
        {
            get
            {
                return this.XMLSendField;
            }
            set
            {
                this.XMLSendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string XMLReceive
        {
            get
            {
                return this.XMLReceiveField;
            }
            set
            {
                this.XMLReceiveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HoldResponse", Namespace="http://accessrsi.com/")]
    public partial class HoldResponse : object
    {
        
        private string CompletionCodeField;
        
        private string CompletionMessageField;
        
        private string InventoryTypeField;
        
        private string ReferenceNumberField;
        
        private string UnitNumberField;
        
        private string StatusField;
        
        private string AuthCodeField;
        
        private bool ErrorField;
        
        private string ErrorMessageField;
        
        private string XMLRequestField;
        
        private string XMLResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionCode
        {
            get
            {
                return this.CompletionCodeField;
            }
            set
            {
                this.CompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionMessage
        {
            get
            {
                return this.CompletionMessageField;
            }
            set
            {
                this.CompletionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InventoryType
        {
            get
            {
                return this.InventoryTypeField;
            }
            set
            {
                this.InventoryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UnitNumber
        {
            get
            {
                return this.UnitNumberField;
            }
            set
            {
                this.UnitNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string XMLRequest
        {
            get
            {
                return this.XMLRequestField;
            }
            set
            {
                this.XMLRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string XMLResponse
        {
            get
            {
                return this.XMLResponseField;
            }
            set
            {
                this.XMLResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddTravelerResponse", Namespace="http://accessrsi.com/")]
    public partial class AddTravelerResponse : object
    {
        
        private string CompletionCodeField;
        
        private string CompletionMessageField;
        
        private bool ErrorField;
        
        private string ErrorMessageField;
        
        private string XMLRequestField;
        
        private string XMLResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionCode
        {
            get
            {
                return this.CompletionCodeField;
            }
            set
            {
                this.CompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionMessage
        {
            get
            {
                return this.CompletionMessageField;
            }
            set
            {
                this.CompletionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XMLRequest
        {
            get
            {
                return this.XMLRequestField;
            }
            set
            {
                this.XMLRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string XMLResponse
        {
            get
            {
                return this.XMLResponseField;
            }
            set
            {
                this.XMLResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TravelerResponse", Namespace="http://accessrsi.com/")]
    public partial class TravelerResponse : object
    {
        
        private string CompletionCodeField;
        
        private string CompletionMessageField;
        
        private string InventoryTypeField;
        
        private string ReferenceNumberField;
        
        private string FirstNameField;
        
        private string MiddleNameField;
        
        private string LastNameField;
        
        private string Address1Field;
        
        private string Address2Field;
        
        private string Address3Field;
        
        private string CityField;
        
        private string StateField;
        
        private string CountryField;
        
        private string PostalCodeField;
        
        private string HomePhoneField;
        
        private string WorkPhoneField;
        
        private bool ErrorField;
        
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionCode
        {
            get
            {
                return this.CompletionCodeField;
            }
            set
            {
                this.CompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompletionMessage
        {
            get
            {
                return this.CompletionMessageField;
            }
            set
            {
                this.CompletionMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string InventoryType
        {
            get
            {
                return this.InventoryTypeField;
            }
            set
            {
                this.InventoryTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceNumber
        {
            get
            {
                return this.ReferenceNumberField;
            }
            set
            {
                this.ReferenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Address3
        {
            get
            {
                return this.Address3Field;
            }
            set
            {
                this.Address3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string HomePhone
        {
            get
            {
                return this.HomePhoneField;
            }
            set
            {
                this.HomePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string WorkPhone
        {
            get
            {
                return this.WorkPhoneField;
            }
            set
            {
                this.WorkPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://accessrsi.com/", ConfigurationName="RCI.XInventoryWSSoap")]
    public interface XInventoryWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/QuickSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.QuickSearchResponse> QuickSearchAsync(RCI.QuickSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/QuickSearchVariable", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.QuickSearchVariableResponse> QuickSearchVariableAsync(RCI.QuickSearchVariableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/ResortSearch", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.ResortSearchResponse> ResortSearchAsync(RCI.ResortSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/RetrieveActivity", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.RetrieveActivityResponse> RetrieveActivityAsync(RCI.RetrieveActivityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/CreateHold", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.CreateHoldResponse> CreateHoldAsync(RCI.CreateHoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/ReleaseHold", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.ReleaseHoldResponse> ReleaseHoldAsync(RCI.ReleaseHoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/Confirm", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.ConfirmResponse> ConfirmAsync(RCI.ConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/ConfirmHold", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.ConfirmHoldResponse> ConfirmHoldAsync(RCI.ConfirmHoldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/AddATraveler", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.AddATravelerResponse> AddATravelerAsync(RCI.AddATravelerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://accessrsi.com/InquireTraveler", ReplyAction="*")]
        System.Threading.Tasks.Task<RCI.InquireTravelerResponse> InquireTravelerAsync(RCI.InquireTravelerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuickSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuickSearch", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.QuickSearchRequestBody Body;
        
        public QuickSearchRequest()
        {
        }
        
        public QuickSearchRequest(RCI.QuickSearchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class QuickSearchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string enddate;
        
        public QuickSearchRequestBody()
        {
        }
        
        public QuickSearchRequestBody(string username, string password, string region, string startdate, string enddate)
        {
            this.username = username;
            this.password = password;
            this.region = region;
            this.startdate = startdate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuickSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuickSearchResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.QuickSearchResponseBody Body;
        
        public QuickSearchResponse()
        {
        }
        
        public QuickSearchResponse(RCI.QuickSearchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class QuickSearchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.ResortResponse[] QuickSearchResult;
        
        public QuickSearchResponseBody()
        {
        }
        
        public QuickSearchResponseBody(RCI.ResortResponse[] QuickSearchResult)
        {
            this.QuickSearchResult = QuickSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuickSearchVariableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuickSearchVariable", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.QuickSearchVariableRequestBody Body;
        
        public QuickSearchVariableRequest()
        {
        }
        
        public QuickSearchVariableRequest(RCI.QuickSearchVariableRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class QuickSearchVariableRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string enddate;
        
        public QuickSearchVariableRequestBody()
        {
        }
        
        public QuickSearchVariableRequestBody(string username, string password, string region, string startdate, string enddate)
        {
            this.username = username;
            this.password = password;
            this.region = region;
            this.startdate = startdate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QuickSearchVariableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QuickSearchVariableResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.QuickSearchVariableResponseBody Body;
        
        public QuickSearchVariableResponse()
        {
        }
        
        public QuickSearchVariableResponse(RCI.QuickSearchVariableResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class QuickSearchVariableResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.ResortResponse[] QuickSearchVariableResult;
        
        public QuickSearchVariableResponseBody()
        {
        }
        
        public QuickSearchVariableResponseBody(RCI.ResortResponse[] QuickSearchVariableResult)
        {
            this.QuickSearchVariableResult = QuickSearchVariableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResortSearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResortSearch", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ResortSearchRequestBody Body;
        
        public ResortSearchRequest()
        {
        }
        
        public ResortSearchRequest(RCI.ResortSearchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ResortSearchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string resortid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string enddate;
        
        public ResortSearchRequestBody()
        {
        }
        
        public ResortSearchRequestBody(string username, string password, string resortid, string startdate, string enddate)
        {
            this.username = username;
            this.password = password;
            this.resortid = resortid;
            this.startdate = startdate;
            this.enddate = enddate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResortSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResortSearchResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ResortSearchResponseBody Body;
        
        public ResortSearchResponse()
        {
        }
        
        public ResortSearchResponse(RCI.ResortSearchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ResortSearchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.ResortResponse[] ResortSearchResult;
        
        public ResortSearchResponseBody()
        {
        }
        
        public ResortSearchResponseBody(RCI.ResortResponse[] ResortSearchResult)
        {
            this.ResortSearchResult = ResortSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveActivityRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveActivity", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.RetrieveActivityRequestBody Body;
        
        public RetrieveActivityRequest()
        {
        }
        
        public RetrieveActivityRequest(RCI.RetrieveActivityRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class RetrieveActivityRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RetrieveActivityRequestBody()
        {
        }
        
        public RetrieveActivityRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveActivityResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveActivityResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.RetrieveActivityResponseBody Body;
        
        public RetrieveActivityResponse()
        {
        }
        
        public RetrieveActivityResponse(RCI.RetrieveActivityResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class RetrieveActivityResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.ResortResponse RetrieveActivityResult;
        
        public RetrieveActivityResponseBody()
        {
        }
        
        public RetrieveActivityResponseBody(RCI.ResortResponse RetrieveActivityResult)
        {
            this.RetrieveActivityResult = RetrieveActivityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateHoldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateHold", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.CreateHoldRequestBody Body;
        
        public CreateHoldRequest()
        {
        }
        
        public CreateHoldRequest(RCI.CreateHoldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class CreateHoldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sessionid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string resortid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string resortname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nbrofbedrooms;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string kitchentype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string maxoccupancy;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string inventoryid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string checkindate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string checkoutdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string price;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int memberID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string website;
        
        public CreateHoldRequestBody()
        {
        }
        
        public CreateHoldRequestBody(
                    string username, 
                    string password, 
                    string sessionid, 
                    string resortid, 
                    string resortname, 
                    string nbrofbedrooms, 
                    string kitchentype, 
                    string maxoccupancy, 
                    string inventorytype, 
                    string inventoryid, 
                    string checkindate, 
                    string checkoutdate, 
                    string price, 
                    string currency, 
                    int memberID, 
                    string website)
        {
            this.username = username;
            this.password = password;
            this.sessionid = sessionid;
            this.resortid = resortid;
            this.resortname = resortname;
            this.nbrofbedrooms = nbrofbedrooms;
            this.kitchentype = kitchentype;
            this.maxoccupancy = maxoccupancy;
            this.inventorytype = inventorytype;
            this.inventoryid = inventoryid;
            this.checkindate = checkindate;
            this.checkoutdate = checkoutdate;
            this.price = price;
            this.currency = currency;
            this.memberID = memberID;
            this.website = website;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateHoldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateHoldResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.CreateHoldResponseBody Body;
        
        public CreateHoldResponse()
        {
        }
        
        public CreateHoldResponse(RCI.CreateHoldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class CreateHoldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.HoldResponse CreateHoldResult;
        
        public CreateHoldResponseBody()
        {
        }
        
        public CreateHoldResponseBody(RCI.HoldResponse CreateHoldResult)
        {
            this.CreateHoldResult = CreateHoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReleaseHoldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReleaseHold", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ReleaseHoldRequestBody Body;
        
        public ReleaseHoldRequest()
        {
        }
        
        public ReleaseHoldRequest(RCI.ReleaseHoldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ReleaseHoldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencenumber;
        
        public ReleaseHoldRequestBody()
        {
        }
        
        public ReleaseHoldRequestBody(string username, string password, string inventorytype, string referencenumber)
        {
            this.username = username;
            this.password = password;
            this.inventorytype = inventorytype;
            this.referencenumber = referencenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReleaseHoldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReleaseHoldResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ReleaseHoldResponseBody Body;
        
        public ReleaseHoldResponse()
        {
        }
        
        public ReleaseHoldResponse(RCI.ReleaseHoldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ReleaseHoldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.HoldResponse ReleaseHoldResult;
        
        public ReleaseHoldResponseBody()
        {
        }
        
        public ReleaseHoldResponseBody(RCI.HoldResponse ReleaseHoldResult)
        {
            this.ReleaseHoldResult = ReleaseHoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Confirm", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ConfirmRequestBody Body;
        
        public ConfirmRequest()
        {
        }
        
        public ConfirmRequest(RCI.ConfirmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ConfirmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencenumber;
        
        public ConfirmRequestBody()
        {
        }
        
        public ConfirmRequestBody(string username, string password, string inventorytype, string referencenumber)
        {
            this.username = username;
            this.password = password;
            this.inventorytype = inventorytype;
            this.referencenumber = referencenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ConfirmResponseBody Body;
        
        public ConfirmResponse()
        {
        }
        
        public ConfirmResponse(RCI.ConfirmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ConfirmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.HoldResponse ConfirmResult;
        
        public ConfirmResponseBody()
        {
        }
        
        public ConfirmResponseBody(RCI.HoldResponse ConfirmResult)
        {
            this.ConfirmResult = ConfirmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmHoldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmHold", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ConfirmHoldRequestBody Body;
        
        public ConfirmHoldRequest()
        {
        }
        
        public ConfirmHoldRequest(RCI.ConfirmHoldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ConfirmHoldRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencenumber;
        
        public ConfirmHoldRequestBody()
        {
        }
        
        public ConfirmHoldRequestBody(string username, string password, string inventorytype, string referencenumber)
        {
            this.username = username;
            this.password = password;
            this.inventorytype = inventorytype;
            this.referencenumber = referencenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmHoldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmHoldResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.ConfirmHoldResponseBody Body;
        
        public ConfirmHoldResponse()
        {
        }
        
        public ConfirmHoldResponse(RCI.ConfirmHoldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class ConfirmHoldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.HoldResponse ConfirmHoldResult;
        
        public ConfirmHoldResponseBody()
        {
        }
        
        public ConfirmHoldResponseBody(RCI.HoldResponse ConfirmHoldResult)
        {
            this.ConfirmHoldResult = ConfirmHoldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddATravelerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddATraveler", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.AddATravelerRequestBody Body;
        
        public AddATravelerRequest()
        {
        }
        
        public AddATravelerRequest(RCI.AddATravelerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class AddATravelerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencenumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string postalcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string homephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string emailaddress;
        
        public AddATravelerRequestBody()
        {
        }
        
        public AddATravelerRequestBody(string username, string password, string inventorytype, string referencenumber, string firstname, string lastname, string address, string city, string state, string country, string postalcode, string homephone, string emailaddress)
        {
            this.username = username;
            this.password = password;
            this.inventorytype = inventorytype;
            this.referencenumber = referencenumber;
            this.firstname = firstname;
            this.lastname = lastname;
            this.address = address;
            this.city = city;
            this.state = state;
            this.country = country;
            this.postalcode = postalcode;
            this.homephone = homephone;
            this.emailaddress = emailaddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddATravelerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddATravelerResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.AddATravelerResponseBody Body;
        
        public AddATravelerResponse()
        {
        }
        
        public AddATravelerResponse(RCI.AddATravelerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class AddATravelerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.AddTravelerResponse AddATravelerResult;
        
        public AddATravelerResponseBody()
        {
        }
        
        public AddATravelerResponseBody(RCI.AddTravelerResponse AddATravelerResult)
        {
            this.AddATravelerResult = AddATravelerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquireTravelerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquireTraveler", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.InquireTravelerRequestBody Body;
        
        public InquireTravelerRequest()
        {
        }
        
        public InquireTravelerRequest(RCI.InquireTravelerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class InquireTravelerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string inventorytype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referencenumber;
        
        public InquireTravelerRequestBody()
        {
        }
        
        public InquireTravelerRequestBody(string username, string password, string inventorytype, string referencenumber)
        {
            this.username = username;
            this.password = password;
            this.inventorytype = inventorytype;
            this.referencenumber = referencenumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InquireTravelerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InquireTravelerResponse", Namespace="http://accessrsi.com/", Order=0)]
        public RCI.InquireTravelerResponseBody Body;
        
        public InquireTravelerResponse()
        {
        }
        
        public InquireTravelerResponse(RCI.InquireTravelerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://accessrsi.com/")]
    public partial class InquireTravelerResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RCI.TravelerResponse InquireTravelerResult;
        
        public InquireTravelerResponseBody()
        {
        }
        
        public InquireTravelerResponseBody(RCI.TravelerResponse InquireTravelerResult)
        {
            this.InquireTravelerResult = InquireTravelerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface XInventoryWSSoapChannel : RCI.XInventoryWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class XInventoryWSSoapClient : System.ServiceModel.ClientBase<RCI.XInventoryWSSoap>, RCI.XInventoryWSSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public XInventoryWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(XInventoryWSSoapClient.GetBindingForEndpoint(endpointConfiguration), XInventoryWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XInventoryWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(XInventoryWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XInventoryWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(XInventoryWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public XInventoryWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.QuickSearchResponse> RCI.XInventoryWSSoap.QuickSearchAsync(RCI.QuickSearchRequest request)
        {
            return base.Channel.QuickSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.QuickSearchResponse> QuickSearchAsync(string username, string password, string region, string startdate, string enddate)
        {
            RCI.QuickSearchRequest inValue = new RCI.QuickSearchRequest();
            inValue.Body = new RCI.QuickSearchRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.region = region;
            inValue.Body.startdate = startdate;
            inValue.Body.enddate = enddate;
            return ((RCI.XInventoryWSSoap)(this)).QuickSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.QuickSearchVariableResponse> RCI.XInventoryWSSoap.QuickSearchVariableAsync(RCI.QuickSearchVariableRequest request)
        {
            return base.Channel.QuickSearchVariableAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.QuickSearchVariableResponse> QuickSearchVariableAsync(string username, string password, string region, string startdate, string enddate)
        {
            RCI.QuickSearchVariableRequest inValue = new RCI.QuickSearchVariableRequest();
            inValue.Body = new RCI.QuickSearchVariableRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.region = region;
            inValue.Body.startdate = startdate;
            inValue.Body.enddate = enddate;
            return ((RCI.XInventoryWSSoap)(this)).QuickSearchVariableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.ResortSearchResponse> RCI.XInventoryWSSoap.ResortSearchAsync(RCI.ResortSearchRequest request)
        {
            return base.Channel.ResortSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.ResortSearchResponse> ResortSearchAsync(string username, string password, string resortid, string startdate, string enddate)
        {
            RCI.ResortSearchRequest inValue = new RCI.ResortSearchRequest();
            inValue.Body = new RCI.ResortSearchRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.resortid = resortid;
            inValue.Body.startdate = startdate;
            inValue.Body.enddate = enddate;
            return ((RCI.XInventoryWSSoap)(this)).ResortSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.RetrieveActivityResponse> RCI.XInventoryWSSoap.RetrieveActivityAsync(RCI.RetrieveActivityRequest request)
        {
            return base.Channel.RetrieveActivityAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.RetrieveActivityResponse> RetrieveActivityAsync(string username, string password)
        {
            RCI.RetrieveActivityRequest inValue = new RCI.RetrieveActivityRequest();
            inValue.Body = new RCI.RetrieveActivityRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((RCI.XInventoryWSSoap)(this)).RetrieveActivityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.CreateHoldResponse> RCI.XInventoryWSSoap.CreateHoldAsync(RCI.CreateHoldRequest request)
        {
            return base.Channel.CreateHoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.CreateHoldResponse> CreateHoldAsync(
                    string username, 
                    string password, 
                    string sessionid, 
                    string resortid, 
                    string resortname, 
                    string nbrofbedrooms, 
                    string kitchentype, 
                    string maxoccupancy, 
                    string inventorytype, 
                    string inventoryid, 
                    string checkindate, 
                    string checkoutdate, 
                    string price, 
                    string currency, 
                    int memberID, 
                    string website)
        {
            RCI.CreateHoldRequest inValue = new RCI.CreateHoldRequest();
            inValue.Body = new RCI.CreateHoldRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.sessionid = sessionid;
            inValue.Body.resortid = resortid;
            inValue.Body.resortname = resortname;
            inValue.Body.nbrofbedrooms = nbrofbedrooms;
            inValue.Body.kitchentype = kitchentype;
            inValue.Body.maxoccupancy = maxoccupancy;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.inventoryid = inventoryid;
            inValue.Body.checkindate = checkindate;
            inValue.Body.checkoutdate = checkoutdate;
            inValue.Body.price = price;
            inValue.Body.currency = currency;
            inValue.Body.memberID = memberID;
            inValue.Body.website = website;
            return ((RCI.XInventoryWSSoap)(this)).CreateHoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.ReleaseHoldResponse> RCI.XInventoryWSSoap.ReleaseHoldAsync(RCI.ReleaseHoldRequest request)
        {
            return base.Channel.ReleaseHoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.ReleaseHoldResponse> ReleaseHoldAsync(string username, string password, string inventorytype, string referencenumber)
        {
            RCI.ReleaseHoldRequest inValue = new RCI.ReleaseHoldRequest();
            inValue.Body = new RCI.ReleaseHoldRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.referencenumber = referencenumber;
            return ((RCI.XInventoryWSSoap)(this)).ReleaseHoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.ConfirmResponse> RCI.XInventoryWSSoap.ConfirmAsync(RCI.ConfirmRequest request)
        {
            return base.Channel.ConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.ConfirmResponse> ConfirmAsync(string username, string password, string inventorytype, string referencenumber)
        {
            RCI.ConfirmRequest inValue = new RCI.ConfirmRequest();
            inValue.Body = new RCI.ConfirmRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.referencenumber = referencenumber;
            return ((RCI.XInventoryWSSoap)(this)).ConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.ConfirmHoldResponse> RCI.XInventoryWSSoap.ConfirmHoldAsync(RCI.ConfirmHoldRequest request)
        {
            return base.Channel.ConfirmHoldAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.ConfirmHoldResponse> ConfirmHoldAsync(string username, string password, string inventorytype, string referencenumber)
        {
            RCI.ConfirmHoldRequest inValue = new RCI.ConfirmHoldRequest();
            inValue.Body = new RCI.ConfirmHoldRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.referencenumber = referencenumber;
            return ((RCI.XInventoryWSSoap)(this)).ConfirmHoldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.AddATravelerResponse> RCI.XInventoryWSSoap.AddATravelerAsync(RCI.AddATravelerRequest request)
        {
            return base.Channel.AddATravelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.AddATravelerResponse> AddATravelerAsync(string username, string password, string inventorytype, string referencenumber, string firstname, string lastname, string address, string city, string state, string country, string postalcode, string homephone, string emailaddress)
        {
            RCI.AddATravelerRequest inValue = new RCI.AddATravelerRequest();
            inValue.Body = new RCI.AddATravelerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.referencenumber = referencenumber;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.address = address;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.country = country;
            inValue.Body.postalcode = postalcode;
            inValue.Body.homephone = homephone;
            inValue.Body.emailaddress = emailaddress;
            return ((RCI.XInventoryWSSoap)(this)).AddATravelerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RCI.InquireTravelerResponse> RCI.XInventoryWSSoap.InquireTravelerAsync(RCI.InquireTravelerRequest request)
        {
            return base.Channel.InquireTravelerAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCI.InquireTravelerResponse> InquireTravelerAsync(string username, string password, string inventorytype, string referencenumber)
        {
            RCI.InquireTravelerRequest inValue = new RCI.InquireTravelerRequest();
            inValue.Body = new RCI.InquireTravelerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.inventorytype = inventorytype;
            inValue.Body.referencenumber = referencenumber;
            return ((RCI.XInventoryWSSoap)(this)).InquireTravelerAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XInventoryWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.XInventoryWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XInventoryWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://accessrsi.com/rsiwebservices/xinventoryws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.XInventoryWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://accessrsi.com/rsiwebservices/xinventoryws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            XInventoryWSSoap,
            
            XInventoryWSSoap12,
        }
    }
}
